### PR TITLE
Initial azure-storage-cli version

### PR DESCRIPTION
**Pull request by mvach**
The azure storage cli is required to solve https://github.com/cloudfoundry/bosh-azure-cpi-release/issues/672.
It still need to be integrated into the director and the agent.

### CODE REVIEW

**Comment by rkoster** [comment]
@jpalermo & @ragaskar do y'all have time to review this PR?

**Review by jpalermo — APPROVED** [review]
Sorry for the delay.

This seems great. I tested the functionality, including on a Windows VM and it all seemed to work.

**Comment by ragaskar** [comment]
I was also able to compile it and run through all the commands in the README you created (thank you!) 

A couple notes: 
* It looks like the comments are flipped in the README for the curl examples, i.e.
```
# Downloading a blob:
curl -X PUT -H "x-ms-blob-type: blockblob" -F ‘fileX=<path/to/file>’ <signed url>

# Uploading a blob:
curl -X GET <signed url>
```

should be

```
# Uploading a blob:
curl -X PUT -H "x-ms-blob-type: blockblob" -F ‘fileX=<path/to/file>’ <signed url>

# Downloading a blob:
curl -X GET <signed url>
```


I found that the `curl` command provided for the PUT did not store my file as I expected but just dumped form-data when I took it literally,. eg, when I set -F `fileX=./test.foo` I got: 

```
--------------------------b44b6325ba33f6fc
Content-Disposition: form-data; name="fileX"

./test.foo
--------------------------b44b6325ba33f6fc--
```

(i.e., used `fileX=`... not sure what I might have done wrong, but might be worth reviewing that snippet for typos). 

But no reason not to merge! Thanks for your patience.

**Review by ragaskar — COMMENTED** [review]
LGTM (see comments above)

**Comment by mvach** [comment]
Hi @ragaskar,
PR https://github.com/cloudfoundry/bosh-azure-storage-cli/pull/2 is addressing your feedback.
THX!

**Pull request merged**
